### ISSUE TITLE
Add Telemetry and Monitoring Support

### ISSUE THREAD

**Issue by runewake2** [Letterbook/Letterbook#116]
We'd like to add telemetry and have dashboards/alerts available in app so that logs, metrics etc can be tracked easily.

- [x] Add open Telemetry Metrics support (#115)
- [x] Add logging support (#124)
- [x] Collect Postgres telemetry (#134)
- [x] Setup default dashboards and auto-provision them (#134)
- [ ] #188
- [x] Support tracing

This is an issue to help w/ tracking some of this work for getting some of this built up.
