### ISSUE TITLE
Admin Features

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#131]
Features that are mainly of interest to instance admins and ops teams

- [ ] Getting started guide
- [ ] Troubleshooting guide
- [ ] Scaling guide
- [ ] Detailed config docs
- [ ] Collection for logs, metrics, and traces
- [ ] Monitoring
