### ISSUE TITLE
Moderation features

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#132]
Tracking features that are mainly of interest to instance moderators or anyone else involved in trust and safety.

- [ ] Local-only posts
- [ ] Moderation notes
- [ ] Assignment tracking to avoid duplicate work
- [ ] Audit log
- [ ] Privileged access to posts (auditable, of course)
- [ ] Spam filtering
- [ ] Mute, suspend, etc actions that automatically expire
- [ ] Fine-grained federation limits

## Summary

The purpose of this issue is to collect ideas and discussions for features that are specifically geared toward moderators. Anything that makes moderation safer, more effective, or more sustainable is appropriate. We also want to consider user-facing features that make the fediverse a safer and healthier place to spend time, or that permit more self-managed moderation for users.

Questions, comments, and suggestions are welcome from anyone who's interested.
