### ISSUE TITLE
Advanced features

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#133]
Tracking features for everything that goes beyond simply posting

- [ ] Quote replies
- [ ] Collapse notifications
- [ ] Block, limit, and remove replies to your posts
- [ ] Propose and accept edits to alt text and content warnings
- [ ] Compose multi-post threads
- [ ] Save drafts and scheduled posts
- [ ] Formatted posts (bold, italics, lists, and block quotes, at least)
- [ ] Emoji reactions

## Summary

The purpose of this issue is to collect ideas and discussions for advanced user features. Anything that makes Letterbook different or more appealing compared to other fedi microblog apps should be considered. Not all of these features will be implemented.

Questions, comments, and suggestions are welcome from anyone who's interested.

**Comment by nenunen** [comment]
I have two UI-related feature suggestions.

1. Option to conveniently anonymize content for screenshots. Censor some/all posts and identities in a way that looks attractive and approximates the true look, preserving the functional meaning of different elements (e.g. censored links should resemble actual links etc.). I believe the feature could help with adoption a lot, because it would make it much easier for everyone to demonstrate the app in genuine contexts and share their experiences and advice. Nobody would have to stage anything, spend long time manipulating images, or worry about their privacy or other people's consent when they capture screenshots or *videos*. Text could be either replaced with meaningless characters or “redacted” with CSS, like [this](https://codepen.io/cheeaun/pen/MWPwbjZ) but with a light color instead of the original black. Applying blur might suit well for censoring images but it's in my opinion unsuitable for texts because it makes text practically disappear, changing the look of everything drastically. This concept drawing I made for another thing is somewhat what I'm for here:
![concept](https://github.com/user-attachments/assets/37e57f07-aa86-4434-8f47-39ad9156f7c8)

2. Instead of imposing hard character limits for posting, just detect when the post the user is writing hits some typical character limits and warn them that their post may get filtered or it will be less visible and readable in some apps others use, or that it may be seen impolite sometimes. Maybe also suggest adding a CW with a short description and offer a preview of how the post would look like in more restrictive apps/configurations. This would be more in line with giving users control over their personal social media experience instead of controlling them.

**Comment by jenniferplusplus** [comment]
The screenshot anonymizer is an interesting idea, but it seems very niche. To be honest, I don't anticipate that I could get to it in the near future. It seems like the best home for something like that would be in a browser extension.

As for character limits, I do plan to have them. Letterbook is mainly a microblogging app. The limits will be configurable, and we'll definitely have a thread editor sooner than not. But brevity is a desirable quality, in my view.

In the longer term, I also want to have a more robust solution for long form posts than to just shove many thousands of characters into a microblog post. My vision for long form content is to support multi-page posts with rich embedded media.
