### ISSUE TITLE
Media features

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#139]
File and media services would allow us to support rich media. That is to say: images, video, and audio. 

## Need
- [ ] Update Image model, if necessary
- [ ] Add core file and/or media services to create and manage media
  - [ ] Be sure to emit events related to things happening with media. We'll likely need a significant amount of background processing for it
- [ ] Add db adapter queries for media
- [ ] Add file adapter
  - [ ] Might be good to support filesystem storage
  - [ ] But the expected path is S3-compatible object storage
- [ ] Add API controllers and actions related to files and media
- [ ] Handle ActivityPub media objects like Image and Video

> [!TIP]
> Update above list as needed, and convert them to issues when they're understood well enough to start development

## Goal
The basic goal is to be able to upload, store, manage, and serve common image formats.

Keep audio, video, and *maybeeee* documents in mind when working on this, but there's no need to implement them, yet. Audio and video are very technically complex. They can also raise particular trust & safety concerns, and can be hard or taxing to moderate. Let's not try to support them right away.

We'll eventually need to do automated scanning, fingerprinting, re-encoding, and maybe other things for audio. But, that's all tremedously complex, and we can start small. Just keep those things in mind, and try to produce events we can utilize to hook into the process later on.
