### ISSUE TITLE
[Epic] Basic posting features

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#140]
The core feature of social media, and microblogs in particular, is to Post :tm:. None of this makes any sense without that. So, we need to build out some basic posting features.

## To Do
- [x] #149
  - [x] Record `Source` and `Content` separately
  - [x] Track a `Context` key, which needs to be queryable ([see fep-7888][fep-7888]) (can be named something else. `Conversation` or `Thread` maybe)
  - [x] Update db entities as needed
  - [x] #154
- [x] #161
- [x] #166
- [x] #176
- [x] Generate Post previews from Content
- [x] #302
- [x] #303
- [x] #304
- [x] #190
- [x] #191

> [!TIP]
> Update above list as needed, and convert them to issues when they're understood well enough to start development

## Goal
When these tasks are done, we should be able to post things, and retrieve things we've posted. Don't worry about feeds or making them available in the inbox/outbox, notifications, or anything else. That can all come later.

[fep-7888]: https://socialhub.activitypub.rocks/t/fep-7888-demystifying-the-context-property/3021

**Comment by jenniferplusplus** [comment]
I've gotten things basically functional, which is a relief. I'm going to put this on the back burner for a while in order to get account and profile management into a usable state.
