### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#301]
Features and improvements I want in the docs site:

- [ ] useful meta tags for social previews
- [ ] RSS feed(s)
- [ ] Author pages (and cross link to posts)

And broken things:

- [ ] static render isn't using the configured markdown pipeline, so we're missing embeds and some other things
- [ ] service stack appHost is janky AF and I want to get rid of it entirely
- [ ] every page renders empty when set to a production environment
